[package]
name = "mdtranslation"
version = "0.1.0"
authors = ["CrLF0710"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
pulldown-cmark = "0.7.0"
pulldown-cmark-to-cmark = "5.0.0"
unicode-segmentation = "1.6.0"
structopt = "0.3.17"
thiserror = "1.0.20"
